"""Add scope models

Revision ID: 3cb799aa1ec5
Revises: f2e984956018
Create Date: 2026-05-12 19:12:30.555421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlmodel import SQLModel


# revision identifiers, used by Alembic.
revision: str = '3cb799aa1ec5'
down_revision: Union[str, Sequence[str], None] = 'f2e984956018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_interest_forms',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('budget_range', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('launch_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deadline_flexibility', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('core_features', sa.JSON(), nullable=True),
    sa.Column('third_party_integrations', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_roles', sa.JSON(), nullable=True),
    sa.Column('concurrent_users', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('existing_codebase', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('existing_tech_stack', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('preferred_tech_stack', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hosting_preference', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('design_or_development', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('top_priority', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('known_constraints', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('compliance_requirements', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_interest_forms_project_name'), 'project_interest_forms', ['project_name'], unique=False)
    op.create_table('scope_requests',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_interest_form_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_input', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_interest_form_id'], ['project_interest_forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scope_requests_project_interest_form_id'), 'scope_requests', ['project_interest_form_id'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope_request_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('langgraph_thread_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'classifying', 'paused', 'analyzing_risks', 'generating_scope', 'completed', 'failed', name='pipelinestatus'), nullable=False),
    sa.Column('current_node', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scope_request_id'], ['scope_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_langgraph_thread_id'), 'pipeline_runs', ['langgraph_thread_id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_scope_request_id'), 'pipeline_runs', ['scope_request_id'], unique=False)
    op.create_table('node_outputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('node_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['scope_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_outputs_pipeline_run_id'), 'node_outputs', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_node_outputs_request_id'), 'node_outputs', ['request_id'], unique=False)
    op.create_table('scope_documents',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pipeline_run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('complexity', sa.Enum('simple', 'mid_tier', 'complex', 'enterprise', name='complexitylevel'), nullable=False),
    sa.Column('complexity_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estimated_cost_min', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_max', sa.Integer(), nullable=True),
    sa.Column('estimated_weeks_min', sa.Integer(), nullable=True),
    sa.Column('estimated_weeks_max', sa.Integer(), nullable=True),
    sa.Column('deliverables', sa.JSON(), nullable=True),
    sa.Column('tech_stack', sa.JSON(), nullable=True),
    sa.Column('timeline_breakdown', sa.JSON(), nullable=True),
    sa.Column('risks', sa.JSON(), nullable=True),
    sa.Column('out_of_scope', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['scope_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scope_documents_request_id'), 'scope_documents', ['request_id'], unique=False)
    op.drop_index(op.f('ix_book_title'), table_name='book')
    op.drop_table('book')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('pages', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('book_pkey'))
    )
    op.create_index(op.f('ix_book_title'), 'book', ['title'], unique=False)
    op.drop_index(op.f('ix_scope_documents_request_id'), table_name='scope_documents')
    op.drop_table('scope_documents')
    op.drop_index(op.f('ix_node_outputs_request_id'), table_name='node_outputs')
    op.drop_index(op.f('ix_node_outputs_pipeline_run_id'), table_name='node_outputs')
    op.drop_table('node_outputs')
    op.drop_index(op.f('ix_pipeline_runs_scope_request_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_langgraph_thread_id'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_scope_requests_project_interest_form_id'), table_name='scope_requests')
    op.drop_table('scope_requests')
    op.drop_index(op.f('ix_project_interest_forms_project_name'), table_name='project_interest_forms')
    op.drop_table('project_interest_forms')
    # ### end Alembic commands ###
